version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    hostname: app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - ENV_MONGODB_USERNAME=drones
      - ENV_MONGODB_PASSWORD=drones123
      - ENV_MONGODB_URI=mongodb://mongodb-host:27017
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    hostname: mongodb-host
    environment:
      - MONGO_INITDB_DATABASE=drones
    ports:
      - 27018:27017
    networks:
      - app-network
    volumes:
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  app-network:
    driver: bridge
